name: NG words

on:
  - push
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-console:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          if grep -rE "console\.(log|dir)" ./src; then
               exit 1
          else
              echo "All good"
          fi
  check-fixme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          if grep -rE "FIXME" ./src; then
               exit 1
          else
              echo "All good"
          fi
