name: Slack notification
on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Send to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
          SLACK_USERNAME: GitHub Actions
          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          SLACK_FOOTER: ''
          SLACK_TITLE: Succeeded
          SLACK_MESSAGE: ${{ github.event.workflow_run.head_commit.message }}
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - uses: actions/checkout@v3
      - name: Send to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
          SLACK_USERNAME: GitHub Actions
          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          SLACK_FOOTER: ''
          SLACK_TITLE: Failed
          SLACK_MESSAGE: ${{ github.event.workflow_run.head_commit.message }} @channel
          SLACK_LINK_NAMES: true
          SLACK_COLOR: danger
