name: Test and lint check

on:
  - push
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Jest
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('yarn.lock') }}
          restore-keys: npm-

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn run build
  test:
    needs: build
    run: npx jest
  lint:
    needs: build
    run: yarn run lint
  check-ng-words:
    needs: build
    run: yarn run check-ngword
